apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  ports:
    - name: audit-service-port
      port: 8084
      protocol: TCP
      targetPort: 8084
      
  selector:
    name: audit-app
    app: onboarding-app
  sessionAffinity: None
  type: ClusterIP