apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-report-app
spec:
  replicas: 1
  selector: 
    matchLabels: 
      name: mysql-report-app
      app: onboarding-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-report-app-pod
      labels: 
        name: mysql-report-app
        app: onboarding-app
    spec:
      containers:
        - name: mysql-report-app
          image: mysql:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-report-db
                  key: db-name
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-report-db
                  key: db-pw
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-report-db
                  key: db-root-pw
          imagePullPolicy: Never
          ports:
            - containerPort: 3306