apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  ports:
    - name: report-service-port
      port: 8083
      protocol: TCP
      targetPort: 8083
      
  selector:
    name: report-app
    app: onboarding-app
  sessionAffinity: None
  type: ClusterIP