apiVersion: v1
kind: Service
metadata:
  name: zookeeper1
  labels:
    name: zookeeper1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    name: zookeeper1
