apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  ports:
    - name: movie-service-port
      port: 8082
      protocol: TCP
      targetPort: 8082
      
  selector:
    name: movie-app
    app: onboarding-app
  sessionAffinity: None
  type: ClusterIP