apiVersion: v1
kind: Pod
metadata:
  name: kibana-pod
  labels:
    app: kibana-pod
spec:
  containers:
    - image: kibana:6.5.4
      name: kibana-pod
      resources:
        limits:
          memory: 2Gi
          cpu: 1.5
      imagePullPolicy: Never
      env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
      ports:
        - containerPort: 5601