apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: 5601-5601
      port: 5601
      protocol: TCP
      targetPort: 5601
  type: ClusterIP
  selector:
    app: kibana-pod