apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - name: 5044-5044
      port: 5044
      protocol: TCP
      targetPort: 5044
  type: ClusterIP
  selector:
    app: logstash-pod