apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - name: auth-service-port
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    name: auth-app
    app: onboarding-app
  sessionAffinity: None
  type: ClusterIP